version: 1.2.1

interface:
  endpointsMenu: true
  modelSelect: true

endpoints:
  custom:
    - name: "SwimGPT"
      baseURL: "https://flowise-to-librechat-production.up.railway.app/v1"
      apiKey: "${ADAPTER_KEY}"
      directEndpoint: false
      models:
        default: ["SwimGPT/SwimGPT 1.0"]
        fetch: false
      dropParams: ["stream"]
      addParams:
        stream: false
        balance: false
      titleConvo: true
      titleModel: "SwimGPT/SwimGPT 1.0"
      modelDisplayLabel: "SwimGPT"
