version: 1.2.1

interface:
  endpointsMenu: true
  modelSelect: true

endpoints:
  custom:
    - name: 'Flowise Adapter'
      baseURL: 'https://flowise-to-librechat-production.up.railway.app/v1'
      apiKey: '${ADAPTER_KEY}'
      directEndpoint: false
      models:
        default: ['flowise/myflow']
        fetch: false
      titleConvo: true
      titleModel: 'flowise/myflow'
      modelDisplayLabel: 'Flowise'
